"""Internationalisation catalogue for the quality-report generator.

Flat catalogue of labels in every supported language plus a `get_labels()`
helper that resolves the effective label set used by `quality_report_generator.py`.

Resolution priority (highest wins):

1. `overrides` dict passed by the caller — wins for the provided keys.
2. Explicit `lang` argument — selects the language from the catalogue.
3. `.agent_lang` file at the root of the packaged agent — written at packaging
   time by `pack_*.sh --lang <code>`. Walks up from CWD and from this file's
   location to find it.
4. `"en"` as final fallback.

For keys missing in the resolved language, the English value is used so the
output is never empty.
"""

from __future__ import annotations

from pathlib import Path


CATALOG: dict[str, dict[str, str]] = {
    "en": {
        # Report title default
        "quality.default_title": "Data Quality Coverage Report",

        # Section headings
        "quality.executive_summary": "Executive Summary",
        "quality.coverage_by_table": "Coverage by Table",
        "quality.existing_rules_detail": "Existing Rules Detail",
        "quality.identified_gaps": "Identified Gaps",
        "quality.rules_created_session": "Rules Created This Session",
        "quality.recommendations": "Recommendations and Next Steps",

        # Meta labels (cover / header)
        "quality.meta.domain": "Domain",
        "quality.meta.collection": "Domain / Collection",
        "quality.meta.scope": "Scope",
        "quality.meta.date": "Date",
        "quality.meta.generation_date": "Generation date",

        # Executive summary table
        "quality.col.metric": "Metric",
        "quality.col.value": "Value",
        "quality.summary.tables_analyzed": "Tables analyzed",
        "quality.summary.existing_rules": "Existing rules",
        "quality.summary.status_breakdown": "Status OK / KO / WARNING",
        "quality.summary.not_executed": "Not executed",
        "quality.summary.estimated_coverage": "Estimated coverage",
        "quality.summary.status_ok": "Status OK",
        "quality.summary.status_ko": "Status KO",
        "quality.summary.status_warning": "Status WARNING",
        "quality.summary.gaps_breakdown": "Critical / moderate / low gaps",
        "quality.summary.gaps_critical": "Critical gaps",
        "quality.summary.gaps_moderate": "Moderate gaps",
        "quality.summary.gaps_low": "Low gaps",
        "quality.summary.rules_created_this_session": "Rules created this session",

        # Coverage table columns
        "quality.col.table": "Table",
        "quality.col.completeness": "Completeness",
        "quality.col.uniqueness": "Uniqueness",
        "quality.col.validity": "Validity",
        "quality.col.consistency": "Consistency",
        "quality.col.coverage": "Coverage",

        # Rules detail table
        "quality.col.rule": "Rule",
        "quality.col.dimension": "Dimension",
        "quality.col.status": "Status",
        "quality.col.pass_pct": "% Pass",
        "quality.col.description": "Description",

        # Gaps table
        "quality.col.priority": "Priority",
        "quality.col.column": "Column",

        # Footer
        "quality.footer": "Generated by Data Quality Agent",

        # HTML lang attribute
        "html.lang_attr": "en",
    },
    "es": {
        "quality.default_title": "Informe de Cobertura de Calidad de Datos",

        "quality.executive_summary": "Resumen Ejecutivo",
        "quality.coverage_by_table": "Cobertura por Tabla",
        "quality.existing_rules_detail": "Detalle de Reglas Existentes",
        "quality.identified_gaps": "Gaps Identificados",
        "quality.rules_created_session": "Reglas Creadas en Esta Sesión",
        "quality.recommendations": "Recomendaciones y Siguientes Pasos",

        "quality.meta.domain": "Dominio",
        "quality.meta.collection": "Dominio / Colección",
        "quality.meta.scope": "Alcance",
        "quality.meta.date": "Fecha",
        "quality.meta.generation_date": "Fecha de generación",

        "quality.col.metric": "Métrica",
        "quality.col.value": "Valor",
        "quality.summary.tables_analyzed": "Tablas analizadas",
        "quality.summary.existing_rules": "Reglas existentes",
        "quality.summary.status_breakdown": "Estado OK / KO / WARNING",
        "quality.summary.not_executed": "No ejecutadas",
        "quality.summary.estimated_coverage": "Cobertura estimada",
        "quality.summary.status_ok": "Estado OK",
        "quality.summary.status_ko": "Estado KO",
        "quality.summary.status_warning": "Estado WARNING",
        "quality.summary.gaps_breakdown": "Gaps críticos / moderados / bajos",
        "quality.summary.gaps_critical": "Gaps críticos",
        "quality.summary.gaps_moderate": "Gaps moderados",
        "quality.summary.gaps_low": "Gaps bajos",
        "quality.summary.rules_created_this_session": "Reglas creadas en esta sesión",

        "quality.col.table": "Tabla",
        "quality.col.completeness": "Completitud",
        "quality.col.uniqueness": "Unicidad",
        "quality.col.validity": "Validez",
        "quality.col.consistency": "Consistencia",
        "quality.col.coverage": "Cobertura",

        "quality.col.rule": "Regla",
        "quality.col.dimension": "Dimensión",
        "quality.col.status": "Estado",
        "quality.col.pass_pct": "% Aprobación",
        "quality.col.description": "Descripción",

        "quality.col.priority": "Prioridad",
        "quality.col.column": "Columna",

        "quality.footer": "Generado por el Agente de Data Quality",

        "html.lang_attr": "es",
    },
}


_AGENT_LANG_FILENAME = ".agent_lang"


def _read_agent_lang() -> str | None:
    """Walk up from CWD and from this file's directory looking for `.agent_lang`."""
    starts = {Path.cwd(), Path(__file__).resolve().parent}
    for start in starts:
        p = start
        while True:
            candidate = p / _AGENT_LANG_FILENAME
            if candidate.is_file():
                try:
                    value = candidate.read_text(encoding="utf-8").strip()
                except OSError:
                    value = ""
                return value or None
            if p.parent == p:
                break
            p = p.parent
    return None


def resolve_lang(lang: str | None = None) -> str:
    """Resolve the effective language. Priority: arg → .agent_lang → 'en'."""
    if lang:
        return lang
    from_file = _read_agent_lang()
    if from_file:
        return from_file
    return "en"


def get_labels(
    lang: str | None = None,
    overrides: dict[str, str] | None = None,
) -> dict[str, str]:
    """Return the resolved label dict for the given language.

    Starts from English so every key is defined. Overlays the chosen language.
    Finally applies caller overrides.
    """
    effective_lang = resolve_lang(lang)

    labels: dict[str, str] = dict(CATALOG["en"])
    if effective_lang != "en" and effective_lang in CATALOG:
        labels.update(CATALOG[effective_lang])

    if overrides:
        labels.update(overrides)

    return labels
